[package]
name = "power_method"
version = "0.1.0"
authors = ["Ben <benjiwhittington@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num="0.2.0"
